FROM grafana/k6:latest
USER root
RUN apk add --update --no-cache vim git make musl-dev go curl chromium
# Configure Go
WORKDIR /go
ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH
ENV PATH=${GOPATH}/bin:${GOROOT}/bin:/usr/local/go/bin:$PATH
ENV GOBIN=$GOROOT/bin
RUN mkdir -p ${GOROOT}/src ${GOROOT}/bin

RUN apk add --update --no-cache git
RUN go env -w GOPROXY=https://proxy.golang.org
RUN git clone https://github.com/grafana/k6.git

COPY . /xk6-playwright-repo
WORKDIR /home/k6/
RUN wget https://unofficial-builds.nodejs.org/download/release/v21.7.1/node-v21.7.1-linux-x64-musl.tar.xz
RUN tar -xvf node-v21.7.1-linux-x64-musl.tar.xz

ENV PATH=/home/k6/node-v21.7.1-linux-x64-musl/bin:$GOPATH/bin:$PATH

WORKDIR /xk6-playwright-repo
RUN go mod download
RUN go install github.com/playwright-community/playwright-go/cmd/playwright

RUN npx playwright install chromium

# Link chromium
RUN export CHROME_FOLDER=$(ls /root/.cache/ms-playwright | grep chromium) \
    && rm -rf /root/.cache/ms-playwright/$CHROME_FOLDER/chrome-linux \
    && ln -s /usr/lib/chromium/ /root/.cache/ms-playwright/$CHROME_FOLDER/chrome-linux

RUN go install go.k6.io/xk6/cmd/xk6
RUN xk6 build v0.41.0 --with github.com/wosp-io/xk6-playwright=$(pwd)

USER k6
WORKDIR /home/k6
